# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
    amocrm.client_id: '55097909-cfd2-4be3-950d-1206a4e40a7e'
    amocrm.client_secret: 'BaZxQcD9EoqlvBS7VgRnprxBQlzOZgd7LlDclz2eW2eIYwq4diYqdecKLanmCJlq'
    amocrm.subdomain: 'ryantodd1176yandexru'
    amocrm.redirect_uri: 'https://f2785bffadbe.ngrok.io/amo/token'
    amocrm.token_file: '%kernel.project_dir%/var/amo_tokens.json'

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
            - '../src/Tests/'

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
